name: Run Jest testing suite
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Knip"]
    types:
      - completed

env:
  NODE_ENV: "test"

jobs:
  testing:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Jest With Coverage Comment
        # Ensures this step is run even on previous step failure (e.g. test failed)
        if: always()
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          prnumber: ${{ github.event.pull_request.number || github.event.workflow_run.pull_requests[0].number }}
